# Generated by Django 5.1.2 on 2024-10-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "marital_status",
                    models.CharField(
                        choices=[("Married", "Married"), ("Single", "Single")],
                        max_length=10,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("i_have_a_car", models.BooleanField(default=False)),
                ("occupation", models.CharField(max_length=100)),
                (
                    "rent_or_own",
                    models.CharField(
                        choices=[("Rent", "Rent"), ("Own", "Own")], max_length=20
                    ),
                ),
                ("application_purpose", models.TextField()),
                ("valid_id", models.FileField(upload_to="id_documents/")),
                ("additional_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
