# Generated by Django 5.1.2 on 2024-10-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_info_gender_alter_info_marital_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="additional_message",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="info",
            name="address",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="info",
            name="age",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="info",
            name="application_purpose",
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name="info",
            name="city",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="info",
            name="email",
            field=models.EmailField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="info",
            name="full_name",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="info",
            name="gender",
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name="info",
            name="i_have_a_car",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="info",
            name="marital_status",
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name="info",
            name="monthly_income",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name="info",
            name="occupation",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="info",
            name="phone_number",
            field=models.CharField(editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name="info",
            name="rent_or_own",
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name="info",
            name="state",
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name="info",
            name="valid_id",
            field=models.FileField(editable=False, upload_to="id_documents/"),
        ),
    ]
