# Generated by Django 5.1.2 on 2024-10-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_info_additional_message_alter_info_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="info",
            name="monthly_income",
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
