# Generated by Django 5.1.2 on 2024-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_info_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="info",
            name="age",
        ),
        migrations.AddField(
            model_name="info",
            name="dob",
            field=models.CharField(default="", editable=False, max_length=16),
        ),
    ]
