# Generated by Django 5.1.2 on 2024-10-28 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_info_age_info_dob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="info",
            options={"ordering": ["-created_at"]},
        ),
    ]
